/**
 * AI Editor Module - Type Definitions
 *
 * Types for the AI Editor feature that analyzes user text
 * and provides editorial suggestions based on the canon.
 */

// ============================================================================
// Public API Types
// ============================================================================

/**
 * Request payload for the AI Editor analyze endpoint
 */
export interface AIEditorAnalyzeRequest {
  text: string;
}

/**
 * Author in a matched camp with detailed insights
 */
export interface AIEditorAuthor {
  /** Author ID for linking to author profile */
  id?: string;
  name: string;
  /** What this author believes about the topic */
  position: string;
  /** Whether they agree or disagree with the user's perspective */
  stance: 'agrees' | 'disagrees' | 'partial';
  /** How this author's ideas specifically align with or counter the user's draft */
  draftConnection: string;
  /** A representative quote from this author */
  quote?: string;
  /** Citation or source link */
  sourceUrl?: string;
}

/**
 * A camp matched to the user's text
 */
export interface AIEditorMatchedCamp {
  campLabel: string;
  /** Plain language explanation of what this perspective means */
  explanation: string;
  topAuthors: AIEditorAuthor[];
}

/**
 * Editorial suggestions generated by the AI Editor
 */
export interface AIEditorEditorialSuggestions {
  /** Perspectives that are present in the text */
  presentPerspectives: string[];
  /** Perspectives that are missing from the text */
  missingPerspectives: string[];
}

/**
 * Executive summary of draft quality
 */
export interface AIEditorExecutiveSummary {
  /** What the draft does well */
  strengths: string[];
  /** How the draft could be improved */
  improvements: string[];
}

/**
 * Response from the AI Editor analyze endpoint
 */
export interface AIEditorAnalyzeResponse {
  /** 2-3 sentence summary of the text */
  summary: string;
  /** Executive summary of strengths and areas for improvement */
  executiveSummary: AIEditorExecutiveSummary;
  /** Camps matched to the text with their top authors */
  matchedCamps: AIEditorMatchedCamp[];
  /** Editorial suggestions based on canon analysis */
  editorialSuggestions: AIEditorEditorialSuggestions;
}

// ============================================================================
// Internal Processing Types
// ============================================================================

/**
 * Camp with its authors, used internally for processing
 */
export interface CampWithAuthors {
  id: string;
  name: string;
  description: string;
  position_summary?: string;
  domain?: string;
  authors: {
    id: string;
    name: string;
    affiliation?: string;
    position_summary?: string;
    relevance?: string;
    /** Real quote from database (camp-specific or author-level) */
    key_quote?: string;
    /** Source URL for the quote */
    quote_source_url?: string;
  }[];
}

/**
 * Extracted keywords from user text
 */
export interface ExtractedKeywords {
  /** Single words extracted from the text */
  words: string[];
  /** Multi-word phrases extracted from the text */
  phrases: string[];
  /** Combined terms for search */
  allTerms: string[];
}

// ============================================================================
// Gemini API Types
// ============================================================================

/**
 * A single text part in Gemini content
 */
export interface GeminiContentPart {
  text: string;
}

/**
 * Content structure for Gemini API
 */
export interface GeminiContent {
  parts: GeminiContentPart[];
}

/**
 * Request body for Gemini API
 */
export interface GeminiRequest {
  contents: GeminiContent[];
}

/**
 * Single candidate in Gemini response
 */
export interface GeminiCandidate {
  content: {
    parts: Array<{
      text: string;
    }>;
  };
}

/**
 * Response from Gemini API
 */
export interface GeminiResponse {
  candidates: GeminiCandidate[];
}

/**
 * Structured analysis result from Gemini
 */
export interface GeminiAnalysisResult {
  summary: string;
  executiveSummary: {
    strengths: string[];
    improvements: string[];
  };
  rankedCamps: Array<{
    campId: string;
    campName: string;
    campExplanation: string;
    relevanceScore: number;
    reasoning: string;
    topAuthors: Array<{
      authorId: string;
      authorName: string;
      position: string;
      stance: 'agrees' | 'disagrees' | 'partial';
      draftConnection: string;
      quote?: string;
      sourceUrl?: string;
    }>;
  }>;
  editorialSuggestions: {
    presentPerspectives: string[];
    missingPerspectives: string[];
  };
}
